### ISSUE TITLE
Update for UE 5.4.3

### ISSUE THREAD

**Issue by LucidMatterBen** [TouchDesigner/TouchEngine-UE4#137]
Howdy!  

Just checking to see when we can expect an update for the new engine version.  My team is using the new version and we're unable to roll-back to the 5.4.1 update that was pushed a while back.  

Thanks for all the hard work!

**Comment by jetXS** [comment]
Having a look - thanks for the report.

**Comment by LucidMatterBen** [comment]
Derivative really is the best, dang.

You're the man!

**Comment by jetXS** [comment]
Hey @LucidMatterBen 

I am not encountering any issue running the latest version of the plugin into 5.4.3. I'd be surprised of any issue since 5.4.x are minor updates that usually don't have an impact.

What is your team struggling with? 

We'd need more details at this point... error messages, build UAT logs.. etc

**Comment by LucidMatterBen** [comment]
Hey @jetXS,

I can't open my project when I attempt to install the plugin.  I created a new Plugins folder at the root of the project and made sure to rename the folder to TouchEngine.  In Unreal, I enabled the plugin through the plugin browser and restarted.  

When attempting to re-open the project I get these errors: 

![Screenshot_16](https://github.com/user-attachments/assets/90a471df-4f20-45a1-b1ce-0c5b666b20ca)
![Screenshot_17](https://github.com/user-attachments/assets/bff14b6c-7199-4d69-abb3-a62aee264bdd)

**Comment by jetXS** [comment]
Hi @LucidMatterBen 

Can you please have a look at the following: https://github.com/TouchDesigner/TouchEngine-UE/blob/UE5.4-Release/docs/FAQ.md#i-have-placed-the-plugin-in-the-plugin-folder-but-my-project-doesnt-start-anymore

Please share the logs so that we get a better idea of the issue.

Best,
Michel

**Comment by LucidMatterBen** [comment]
@jetXS 

Just installed the Build Tools for VS and still not working.  Here's the log file though.  I'm not at all versed enough to understand what it means and tried searching a few lines but was in over my 
head.  Could you check it out for me?

[H_ClothingDemo_v002-backup-2024.08.16-21.06.19.log](https://github.com/user-attachments/files/16641764/H_ClothingDemo_v002-backup-2024.08.16-21.06.19.log)

Thank you!

**Comment by jetXS** [comment]
Hi @LucidMatterBen 

The errors in the log file are unrelated to TouchEngine.

```
Unhandled exception: System.AggregateException: One or more errors occurred. (Could not find a part of the path 'X:\UE_5.4\Engine\Plugins\Marketplace\Draper'.)
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'X:\UE_5.4\Engine\Plugins\Marketplace\Draper'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.FileInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.DirectoryInfo.GetFiles(String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.DirectoryInfo.GetFiles()
   at UnrealBuildBase.DirectoryItem.CacheFiles() in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\Shared\EpicGames.Build\System\DirectoryItem.cs:line 289
   at UnrealBuildBase.PluginsBase.EnumeratePluginsInternal(DirectoryItem ParentDirectory, List`1 FileNames, ThreadPoolWorkQueue Queue) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\Shared\EpicGames.Build\System\EnumeratePlugins.cs:line 89
   at UnrealBuildBase.PluginsBase.<>c__DisplayClass5_1.<EnumeratePluginsInternal>b__0() in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\Shared\EpicGames.Build\System\EnumeratePlugins.cs:line 107
   at EpicGames.Core.ThreadPoolWorkQueue.Execute(Object actionToExecute) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\Shared\EpicGames.Core\ThreadPoolWorkQueue.cs:line 98
   --- End of inner exception stack trace ---
   at EpicGames.Core.ThreadPoolWorkQueue.RethrowExceptions() in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\Shared\EpicGames.Core\ThreadPoolWorkQueue.cs:line 167
   at EpicGames.Core.ThreadPoolWorkQueue.Dispose() in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\Shared\EpicGames.Core\ThreadPoolWorkQueue.cs:line 63
   at UnrealBuildBase.PluginsBase.<>c__DisplayClass4_0.<EnumeratePlugins>b__0(DirectoryReference _) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\Shared\EpicGames.Build\System\EnumeratePlugins.cs:line 69
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at UnrealBuildBase.PluginsBase.EnumeratePlugins(DirectoryReference ParentDirectory) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\Shared\EpicGames.Build\System\EnumeratePlugins.cs:line 59
   at UnrealBuildBase.Rules.FindAllRulesSourceFiles(RulesFileType RulesFileType, List`1 GameFolders, List`1 ForeignPlugins, List`1 AdditionalSearchPaths, Boolean bIncludeEngine, Boolean bIncludeTempTargets) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\Shared\EpicGames.Build\System\Rules.cs:line 89
   at UnrealBuildBase.CompileScriptModule.InitializeScriptModules(RulesFileType RulesFileType, String ScriptsForProjectFileName, List`1 AdditionalScriptsFolders, Boolean bForceCompile, Boolean bNoCompile, Boolean bUseBuildRecords, Boolean& bBuildSuccess, Action`1 OnBuildingProjects, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\Shared\EpicGames.Build\System\CompileScriptModules.cs:line 168
   at AutomationToolDriver.Program.MainProc() in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\AutomationTool\Program.cs:line 485
AutomationTool executed for 0h 0m 0s
AutomationTool exiting with ExitCode=1 (Error_Unknown)
```

**Comment by LucidMatterBen** [comment]
@jetXS 

You're a legend, thank you.  I accidentally broke that plugin, but fully removing it fixed everything.  Apologies for my stupidity.
